server:
  port: 9100
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: bc8e1fbe-b195-49bf-a754-939d384515e7 # 默认public注册