server:
  port: ${port:9001}
spring:
  application:
    name: pay-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: bc8e1fbe-b195-49bf-a754-939d384515e7 # 默认public注册
#        group: MY_GROUP
  profiles:
    active: dev